### ISSUE TITLE
"用法 h,s,p,n,z 代表橫、豎、撇、捺、折"

### ISSUE THREAD

**Issue by hiuwo** [rime/rime-stroke#8]
"用法 h,s,p,n,z 代表橫、豎、撇、捺、折"

應該係wspnz 唔係hspnz

**Comment by hiuwo** [comment]
你誤會左我意思，我唔係feature request。
我係想表達你個readme 寫橫係 h ， 但係下載咗配方後，打h 冇反應，yaml入面係寫w。至少喺我部電腦係要打w 先肯出字。

**Comment by LEOYoon-Tsaw** [comment]
係咪改咗過？原版係用h打橫嘅
